/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEWbiblioteca;

import DAObiblioteca.PrincipalDAO;
import DTObiblioteca.PrincipalDTO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
//import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;

import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author clsedu
 */
public class FrmPrincipalVIEW extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipalVIEW
     */
    public FrmPrincipalVIEW() {
        initComponents();
        listarLivros();
        this.setExtendedState(MAXIMIZED_BOTH);
        
        //data do sistema
        Date dataSistema = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        lbl_data.setText(formato.format(dataSistema));
        
        //hora
        Timer timer = new Timer(1000, new hora() {});
        timer.start();
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_titulo = new javax.swing.JLabel();
        txt_titulo_livro = new javax.swing.JTextField();
        lbl_autor = new javax.swing.JLabel();
        txt_autor_livro = new javax.swing.JTextField();
        lbl_editora = new javax.swing.JLabel();
        lbl_edicao = new javax.swing.JLabel();
        lbl_ano = new javax.swing.JLabel();
        txt_editora_livro = new javax.swing.JTextField();
        txt_edicao_livro = new javax.swing.JTextField();
        txt_ano_livro = new javax.swing.JTextField();
        btn_cadastrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_data = new javax.swing.JLabel();
        lbl_hora = new javax.swing.JLabel();
        btn_cadastrar1 = new javax.swing.JButton();
        btn_consultar = new javax.swing.JButton();
        btn_cadastrar3 = new javax.swing.JButton();
        lbl_user = new javax.swing.JLabel();
        lbl_logado = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_livros = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Cadastro de Livros");

        lbl_titulo.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lbl_titulo.setText("Título:");

        txt_titulo_livro.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N

        lbl_autor.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lbl_autor.setText("Autor(a)s:");

        txt_autor_livro.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N

        lbl_editora.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lbl_editora.setText("Editora:");

        lbl_edicao.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lbl_edicao.setText("Edição:");

        lbl_ano.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lbl_ano.setText("Ano:");

        txt_editora_livro.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N

        txt_edicao_livro.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N

        txt_ano_livro.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N

        btn_cadastrar.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btn_cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar-48.png"))); // NOI18N
        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(180, 176, 170));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setText("Cadastro de Livros");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/livros-48.png"))); // NOI18N

        lbl_data.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lbl_data.setText("jLabel3");

        lbl_hora.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lbl_hora.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
                .addComponent(lbl_data)
                .addGap(18, 18, 18)
                .addComponent(lbl_hora)
                .addContainerGap(250, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbl_data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_hora))
                .addGap(57, 57, 57))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_cadastrar1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btn_cadastrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lápis-48.png"))); // NOI18N
        btn_cadastrar1.setText("Alterar");
        btn_cadastrar1.setMaximumSize(new java.awt.Dimension(150, 62));
        btn_cadastrar1.setMinimumSize(new java.awt.Dimension(150, 62));
        btn_cadastrar1.setPreferredSize(new java.awt.Dimension(150, 62));

        btn_consultar.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btn_consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar-48.png"))); // NOI18N
        btn_consultar.setText("Consultar");
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });

        btn_cadastrar3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btn_cadastrar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir-48.png"))); // NOI18N
        btn_cadastrar3.setLabel("  Excluir");
        btn_cadastrar3.setMaximumSize(new java.awt.Dimension(150, 62));
        btn_cadastrar3.setMinimumSize(new java.awt.Dimension(150, 62));
        btn_cadastrar3.setPreferredSize(new java.awt.Dimension(150, 62));

        lbl_user.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lbl_user.setForeground(new java.awt.Color(34, 123, 241));
        lbl_user.setText("jLabel3");

        lbl_logado.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lbl_logado.setText("Usuário:");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        tbl_livros.setAutoCreateRowSorter(true);
        tbl_livros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Title 2", "Title 3", "Title 4", "null", "Ano"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_livros.setPreferredSize(new java.awt.Dimension(900, 72));
        tbl_livros.setShowGrid(true);
        jScrollPane2.setViewportView(tbl_livros);
        if (tbl_livros.getColumnModel().getColumnCount() > 0) {
            tbl_livros.getColumnModel().getColumn(0).setResizable(false);
            tbl_livros.getColumnModel().getColumn(0).setPreferredWidth(45);
            tbl_livros.getColumnModel().getColumn(5).setResizable(false);
            tbl_livros.getColumnModel().getColumn(5).setPreferredWidth(40);
        }

        jScrollPane3.setViewportView(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_editora)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_autor)
                                .addComponent(lbl_titulo, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_titulo_livro)
                                    .addComponent(txt_autor_livro, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(txt_editora_livro, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_edicao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_edicao_livro, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(130, 130, 130)
                                .addComponent(lbl_ano)
                                .addGap(27, 27, 27)
                                .addComponent(txt_ano_livro, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_cadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cadastrar)
                    .addComponent(btn_cadastrar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_consultar))
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lbl_logado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_user)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_logado)
                            .addComponent(lbl_user))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_titulo_livro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_titulo)
                            .addComponent(btn_cadastrar))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_cadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_autor_livro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_autor))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_ano_livro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_ano)
                                    .addComponent(txt_edicao_livro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_edicao)
                                    .addComponent(txt_editora_livro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_editora)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(btn_cadastrar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_consultar)))
                .addGap(94, 94, 94))
        );

        setSize(new java.awt.Dimension(1312, 775));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        
       
        cadastrarlivros();
          
        
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed
        // 
        listarLivros();
    }//GEN-LAST:event_btn_consultarActionPerformed

   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipalVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_cadastrar1;
    private javax.swing.JButton btn_cadastrar3;
    private javax.swing.JButton btn_consultar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_ano;
    private javax.swing.JLabel lbl_autor;
    private javax.swing.JLabel lbl_data;
    private javax.swing.JLabel lbl_edicao;
    private javax.swing.JLabel lbl_editora;
    private javax.swing.JLabel lbl_hora;
    private javax.swing.JLabel lbl_logado;
    private javax.swing.JLabel lbl_titulo;
    public javax.swing.JLabel lbl_user;
    private javax.swing.JTable tbl_livros;
    private javax.swing.JTextField txt_ano_livro;
    private javax.swing.JTextField txt_autor_livro;
    private javax.swing.JTextField txt_edicao_livro;
    private javax.swing.JTextField txt_editora_livro;
    private javax.swing.JTextField txt_titulo_livro;
    // End of variables declaration//GEN-END:variables

public void limparCampos(){
    txt_titulo_livro.setText("");
    txt_autor_livro.setText("");
    txt_editora_livro.setText("");
    txt_edicao_livro.setText("");
    txt_ano_livro.setText("");
    txt_titulo_livro.requestFocus();
}


private void cadastrarlivros(){
    
     String titulo, autor, editora, edicao;
        int codigo, ano;
        
        //codigo = Integer.parseInt(txt_codigo_livro.getText());
        titulo = txt_titulo_livro.getText().toUpperCase();
        autor = txt_autor_livro.getText().toUpperCase();
        editora = txt_editora_livro.getText().toUpperCase();
        edicao = txt_edicao_livro.getText().toUpperCase();
        ano = Integer.parseInt(txt_ano_livro.getText());
        
        
        PrincipalDTO objprincipaldto = new PrincipalDTO();
       // objprincipaldto.setCodigo_livro(codigo);
        objprincipaldto.setTitulo_livro(titulo);
        objprincipaldto.setAutor_livro(autor);
        objprincipaldto.setEditora_livro(editora);
        objprincipaldto.setEdicao_livro(edicao);
        objprincipaldto.setAno_livro(ano);
        
        
        PrincipalDAO objprincipaldao = new PrincipalDAO();
        objprincipaldao.cadastrarLivro(objprincipaldto);
        
        limparCampos();
    
    
}
   

private void listarLivros(){
    try {
        PrincipalDAO objprincipaldao = new PrincipalDAO();
        
        
        DefaultTableModel model = (DefaultTableModel) tbl_livros.getModel();
        model.setNumRows(0);
        
        ArrayList<PrincipalDTO> lista = objprincipaldao.PesquisarLivro();
        
        for(int num = 0; num < lista.size(); num++){
            model.addRow(new Object[]{
                 lista.get(num).getId_codigo_livro(),
                 lista.get(num).getTitulo_livro(),
                 lista.get(num).getAutor_livro(),
                 lista.get(num).getEditora_livro(),
                 lista.get(num).getEdicao_livro(),
                 lista.get(num).getAno_livro()
            });
        }
        
        
    } catch (Exception erro) {
        JOptionPane.showMessageDialog(null, "Listar livros VIEW" + erro);
    }
}

abstract class hora implements ActionListener{
    @Override
    public void actionPerformed(ActionEvent e){
        Calendar now = Calendar.getInstance();
        lbl_hora.setText(String.format("%1$tH:%1$tM:%1$tS", now));
    }
}



}
